/**
 * What a function is told about the call it is serving.
 *
 * Handed to the handler as its second argument. Per-invocation values used to be injected into the
 * process environment and read with Deno.env.get, which is global: two concurrent calls saw each
 * other's configuration, including a service-role key granted to one route and not another. The
 * worker therefore held a lock across every handler and ran one invocation at a time.
 *
 * Passing them in removes the global, so functions run concurrently.
 *
 * Regenerated by the CLI. Edits are overwritten.
 */
export interface FunctionContext {
  /** Unique to this invocation. Every log line it writes carries the same value. */
  readonly executionId: string
  /** The function or hook route being served. */
  readonly functionName: string
  /** The project's API base URL, reachable from inside the function. */
  readonly url: string
  readonly anonKey: string
  /** Present only when the project granted this route the service role. */
  readonly serviceRoleKey?: string
  readonly dbUrl?: string
  readonly region: string
  /** Values from .env and .env.<function>.local. */
  readonly env: Readonly<Record<string, string>>
}
