// Generated by supatype-engine — do not edit manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      todo: {
        Row: {
          id: string
          title: string
          done: boolean
          owner_id: string
          created_at: string
        }
        Insert: {
          id?: string
          title: string
          done: boolean
          owner_id: string
          created_at: string
        }
        Update: {
          id?: string
          title?: string
          done?: boolean
          owner_id?: string
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}