// ─── Admin Configuration JSON ───────────────────────────────────────────────────
// This is the shape of the configuration JSON generated by the engine's
// `admin` subcommand. The admin panel reads this to render dynamic views.

export type WidgetType =
  | "text"
  | "textarea"
  | "number"
  | "boolean"
  | "date"
  | "datetime"
  | "select"
  | "richtext"
  | "image"
  | "file"
  | "relation"
  | "multirelation"
  | "json"
  | "blocks"
  | "publish"
  | "slug"
  | "email"
  | "url"
  | "uuid"
  | "color"

export interface FieldConfig {
  name: string
  label: string
  widget: WidgetType
  required: boolean
  localized: boolean
  /** Field-specific options (e.g. enum values, relation target, block types). */
  options?: Record<string, unknown>
  /** Validation rules (min, max, maxLength, pattern, etc.). */
  validation?: Record<string, unknown>
  /** Whether this field appears in the list view column. */
  listColumn?: boolean
  /** Column width hint for list view. */
  listWidth?: number
  /** Whether this field is searchable in list view. */
  searchable?: boolean
  /** Whether this field is filterable in list view. */
  filterable?: boolean
  /** Whether this field is sortable in list view. */
  sortable?: boolean
  /** Display order in edit view. */
  order?: number
  /** Admin override: hide this field from the edit form. */
  hidden?: boolean
  /** Admin override: make this field read-only in the edit form. */
  readOnly?: boolean
}

export interface BlockTypeConfig {
  name: string
  label: string
  icon?: string
  fields: FieldConfig[]
}

export interface ModelConfig {
  /** Internal model name. */
  name: string
  /** Human-readable label (singular). */
  label: string
  /** Human-readable label (plural). */
  labelPlural: string
  /** PostgREST table path. */
  tableName: string
  /** API path for CRUD. */
  apiPath: string
  /** Primary key field name. */
  primaryKey: string
  /** Field configurations for edit view. */
  fields: FieldConfig[]
  /** List view column order (field names). */
  listColumns: string[]
  /** Fields included in text search. */
  searchFields: string[]
  /** Whether this model has publishable workflow. */
  publishable: boolean
  /** Whether this model has versioning enabled. */
  versioning: boolean
  /** Whether this model has soft delete. */
  softDelete: boolean
  /** Whether this model has timestamps. */
  timestamps: boolean
  /** Whether this model has hooks configured. */
  hasHooks: boolean
}

export interface GlobalConfig {
  name: string
  label: string
  tableName: string
  apiPath: string
  fields: FieldConfig[]
}

export interface NavGroup {
  label: string
  icon?: string
  items: NavItem[]
}

export interface NavItem {
  label: string
  icon?: string
  href: string
  type: "model" | "global" | "media" | "dashboard" | "custom"
}

export interface LocaleConfigAdmin {
  locales: Array<{ code: string; label: string }>
  defaultLocale: string
}

export interface BrandingConfig {
  logo?: string
  favicon?: string
  primaryColor?: string
  appName?: string
}

export interface LivePreviewConfig {
  url: string
  /** URL pattern with {field} placeholders, e.g. "/blog/{slug}" */
  urlPattern?: string
}

export interface AdminConfig {
  models: ModelConfig[]
  globals: GlobalConfig[]
  navigation: NavGroup[]
  locale?: LocaleConfigAdmin
  branding?: BrandingConfig
  livePreview?: Record<string, LivePreviewConfig>
  /** Custom dashboard widgets (placeholder for override system). */
  dashboard?: DashboardConfig
}

export interface DashboardWidget {
  type: "stats" | "recent" | "chart" | "custom"
  title: string
  model?: string
  options?: Record<string, unknown>
}

export interface DashboardConfig {
  widgets: DashboardWidget[]
}
