// Generated by supatype CLI, do not edit manually.
//
// Typed handlers for the models that declare `hooks`. Import from a function beside it:
//
//   import { hook, type BeforeChange } from "../_supatype/hooks.ts"
//
//   const moderate: BeforeChange<"posts"> = async (ctx) => {
//     if (ctx.operation === "insert") return { rows: ctx.rows }
//     return {}
//   }
//
//   export default hook(moderate)
//
// One function can serve a model's whole lifecycle instead, since the worker takes one default
// export per directory:
//
//   export default hooks({
//     beforeChange: moderate,
//     afterChange: reindex,
//   })

/**
 * Lexical editor state as JSON, or the plain string accepted for seeds and defaults.
 *
 * Structural rather than imported: the precise `SerializedEditorState` lives in
 * `@supatype/types/lexical`, which a Deno function has no way to resolve.
 */
export type RichTextValue = { readonly root: { readonly children: readonly unknown[] } } | string

export interface HookTables {
  "product": {
    Row: {
      availableFrom: string | null
      availableUntil: string | null
      description: (RichTextValue | string) | null
      headline: string | null
      id: string
      name: string
      notes: Record<string, unknown> | null
      rating: number | null
      setupItems: Record<string, unknown> | null
      sku: string | null
      slug: string | null
      status: "draft" | "published"
      tags: Record<string, unknown> | null
    }
    Insert: {
      availableFrom?: string | null
      availableUntil?: string | null
      description?: (RichTextValue | string) | null
      headline?: string | null
      id?: string
      name: string
      notes?: Record<string, unknown> | null
      rating?: number | null
      setupItems?: Record<string, unknown> | null
      sku?: string | null
      slug?: string | null
      status: "draft" | "published"
      tags?: Record<string, unknown> | null
    }
    Update: {
      availableFrom?: string | null
      availableUntil?: string | null
      description?: (RichTextValue | string) | null
      headline?: string | null
      id?: string
      name?: string
      notes?: Record<string, unknown> | null
      rating?: number | null
      setupItems?: Record<string, unknown> | null
      sku?: string | null
      slug?: string | null
      status?: "draft" | "published"
      tags?: Record<string, unknown> | null
    }
  }
}

/** Only the tables that declare a hook, so `BeforeChange<"unhooked">` is a compile error. */
export type HookedTable = keyof HookTables & string

interface HookBase {
  readonly table: string
  /** Claims from the JWT the server already verified. `null` for an anonymous caller. */
  readonly user: { readonly sub: string; readonly role: string; readonly email?: string } | null
  /** Correlates this hook with the request in server logs. */
  readonly requestId: string
}

/**
 * The rows this request is about to overwrite, fetched only if you ask.
 *
 * Resolved by the server from the in-flight request's own filter, as the caller's own role, so it
 * cannot show you rows the caller could not read, and you cannot widen the filter. Capped:
 * `truncated` is true when there were more, in which case acting on what you got means acting on a
 * prefix you did not choose.
 */
export type PreviousRows<T extends HookedTable> = () => Promise<{
  rows: HookTables[T]["Row"][]
  truncated: boolean
}>

export type BeforeChangeContext<T extends HookedTable> =
  | (HookBase & { readonly operation: "insert"; readonly rows: HookTables[T]["Insert"][] })
  | (HookBase & {
      readonly operation: "update"
      readonly patch: HookTables[T]["Update"]
      /** PostgREST filter from the request, e.g. `status=eq.draft`. Not rewritable. */
      readonly filter: string
      readonly previous: PreviousRows<T>
    })

export type BeforeDeleteContext<T extends HookedTable> = HookBase & {
  readonly operation: "delete"
  readonly filter: string
  readonly previous: PreviousRows<T>
}

export type AfterChangeContext<T extends HookedTable> = HookBase & {
  readonly operation: "insert" | "update"
  /** Written rows: present only when the caller sent `Prefer: return=representation`. */
  readonly rows?: HookTables[T]["Row"][]
}

export type AfterDeleteContext<T extends HookedTable> = HookBase & {
  readonly operation: "delete"
  readonly filter: string
}

/** Reject with a message, or with a status of your choosing. */
export interface HookRejection {
  readonly reject: string | { readonly message: string; readonly status?: number; readonly code?: string }
}

export type BeforeChangeVerdict<T extends HookedTable> =
  | Record<string, never>
  | { readonly rows: HookTables[T]["Insert"][] }
  | { readonly patch: HookTables[T]["Update"] }
  | HookRejection

export type BeforeDeleteVerdict = Record<string, never> | HookRejection

export type BeforeChange<T extends HookedTable> = (
  ctx: BeforeChangeContext<T>,
) => BeforeChangeVerdict<T> | Promise<BeforeChangeVerdict<T>>

export type BeforeDelete<T extends HookedTable> = (
  ctx: BeforeDeleteContext<T>,
) => BeforeDeleteVerdict | Promise<BeforeDeleteVerdict>

export type AfterChange<T extends HookedTable> = (
  ctx: AfterChangeContext<T>,
) => void | Promise<void>

export type AfterDelete<T extends HookedTable> = (
  ctx: AfterDeleteContext<T>,
) => void | Promise<void>


/**
 * A per-field validator: one field's value, and a verdict about it.
 *
 * `FieldValidator<"products", "setup_items">` types `value` as that column's real type, so a
 * validator cannot quietly be written against the wrong shape.
 *
 * Return `true` to accept, or a message to refuse. The message reaches the caller attached to the
 * field name, which is what lets a form put it on the input rather than in a banner: the whole
 * reason for declaring this instead of putting the same logic in a `beforeChange` hook.
 */
export type FieldValidatorContext<T extends HookedTable, F extends keyof HookTables[T]["Row"]> =
  HookBase & {
    readonly operation: "insert" | "update"
    readonly field: F
    readonly value: HookTables[T]["Row"][F]
  }

export type FieldVerdict = true | string

export type FieldValidator<T extends HookedTable, F extends keyof HookTables[T]["Row"]> = (
  ctx: FieldValidatorContext<T, F>,
) => FieldVerdict | Promise<FieldVerdict>

interface WireValidatorContext {
  table?: string
  operation?: string
  field?: string
  value?: unknown
  user?: unknown
  requestId?: string
}

/**
 * Wrap a typed validator as the request handler the worker expects.
 *
 * A refusal is **422 with the field named**, not a bare 400: the request was understood and one
 * value was rejected. A thrown error is deliberately *not* turned into a refusal, because a broken
 * validator has not decided anything: it becomes a 500, which the server reads as unavailable and
 * refuses the write on, rather than as the validator saying no.
 */
export function fieldValidator(
  handler: (ctx: never) => FieldVerdict | Promise<FieldVerdict>,
): (req: Request) => Promise<Response> {
  return async (req: Request): Promise<Response> => {
    if (req.method !== "POST") {
      return json({ message: "A validator is invoked with POST" }, 405)
    }

    let wire: WireValidatorContext
    try {
      wire = (await req.json()) as WireValidatorContext
    } catch {
      return json({ message: "Validator payload was not JSON" }, 400)
    }

    const field = wire.field ?? ""
    const ctx = {
      table: wire.table ?? "",
      operation: wire.operation === "update" ? "update" : "insert",
      field,
      value: wire.value,
      user: (wire.user ?? null) as never,
      requestId: wire.requestId ?? "",
    }

    const verdict = await handler(ctx as never)
    if (verdict === true) return json({}, 200)
    return json({ field, message: String(verdict), error: String(verdict) }, 422)
  }
}

/** Every handler a single function may serve, when one function covers a model's whole lifecycle. */
export interface HookHandlers<T extends HookedTable> {
  readonly beforeChange?: BeforeChange<T>
  readonly beforeDelete?: BeforeDelete<T>
  readonly afterChange?: AfterChange<T>
  readonly afterDelete?: AfterDelete<T>
}

type AnyHandler = (ctx: never) => unknown

interface WireContext {
  table?: string
  operation?: string
  user?: unknown
  requestId?: string
  rows?: unknown[]
  patch?: unknown
  filter?: string
  /**
   * Server callback **path** for pre-write rows; absent when there are none to fetch.
   *
   * A path rather than a URL because the server does not know its own in-network address, while this
   * worker is already told how to reach the stack.
   */
  previousPath?: string
}

/**
 * Wrap a typed handler as the request handler the worker expects.
 *
 * The outcome travels as the **HTTP status**: 200 for proceed, 4xx for a rejection. That keeps the
 * contract in the transport rather than in a second envelope inside the body, so a hook written by
 * hand: or in another language, needs to know nothing about this file.
 */
export function hook(handler: AnyHandler): (req: Request) => Promise<Response> {
  return async (req: Request): Promise<Response> => {
    if (req.method !== "POST") {
      return json({ message: "A hook is invoked with POST" }, 405)
    }

    let wire: WireContext
    try {
      wire = (await req.json()) as WireContext
    } catch {
      // A 400 rather than a 500: the payload was wrong, the handler never ran.
      return json({ message: "Hook payload was not JSON" }, 400)
    }

    const signature = req.headers.get("webhook-signature")
    const ctx = {
      table: wire.table ?? "",
      operation: wire.operation ?? "",
      user: wire.user ?? null,
      requestId: wire.requestId ?? "",
      ...(wire.rows !== undefined && { rows: wire.rows }),
      ...(wire.patch !== undefined && { patch: wire.patch }),
      ...(wire.filter !== undefined && { filter: wire.filter }),
      ...(wire.previousPath !== undefined && {
        previous: () => fetchPrevious(wire.previousPath as string, signature),
      }),
    }

    let verdict: unknown
    try {
      verdict = await handler(ctx as never)
    } catch (err) {
      // An exception is not a rejection: the hook broke, so the server's onUnavailable policy should
      // decide, and that is what a 500 asks for.
      return json({ message: err instanceof Error ? err.message : "Hook threw" }, 500)
    }

    if (verdict === undefined || verdict === null) return json({}, 200)

    const rejection = (verdict as HookRejection).reject
    if (rejection !== undefined) {
      const detail = typeof rejection === "string" ? { message: rejection } : rejection
      const status = typeof detail.status === "number" ? detail.status : 422
      return json(
        { message: detail.message, ...(detail.code !== undefined && { code: detail.code }) },
        // A rejection must be a 4xx: a hook that answered 500 would be read as unavailable and
        // handed to onUnavailable, which is a different decision from "no".
        status >= 400 && status < 500 ? status : 422,
      )
    }

    return json(verdict as Record<string, unknown>, 200)
  }
}

/**
 * Serve several of a model's hooks from one function, dispatched on `X-Supatype-Hook`.
 *
 * The worker takes **one default export per function directory**, so `hook(single)` is one hook per
 * directory. That is fine for a single moderation rule and tedious for a model whose whole lifecycle
 * you want in one place, hence this. Point every event at the same function name in the schema:
 *
 *   hooks: { beforeChange: "post-hooks", afterChange: "post-hooks" }
 *
 * An event arriving with no handler is a 200, not an error: the schema and this file can be out of
 * step for one deploy, and failing a write because the *other* half has not shipped yet would be the
 * wrong way round.
 */
export function hooks(handlers: Record<string, AnyHandler | undefined>): (req: Request) => Promise<Response> {
  return async (req: Request): Promise<Response> => {
    const event = req.headers.get("x-supatype-hook") ?? ""
    const handler = handlers[event]
    if (handler === undefined) return json({}, 200)
    return hook(handler)(req)
  }
}

/**
 * The stack's address from this worker's point of view.
 *
 * `SUPATYPE_INTERNAL_URL` in Compose is the in-network gateway; `SUPATYPE_URL` is the same value
 * there. Never a public or host URL, `localhost` inside this container is this container.
 */
function stackBaseUrl(): string {
  const base =
    Deno.env.get("SUPATYPE_INTERNAL_URL") ??
    Deno.env.get("SUPATYPE_URL") ??
    ""
  if (base === "") {
    throw new Error(
      "ctx.previous() needs SUPATYPE_INTERNAL_URL or SUPATYPE_URL to reach the API from this function",
    )
  }
  // No regex: a backslash in a template literal is one escape away from emitting broken code, and a
  // generator's output has to be right the first time.
  return base.endsWith("/") ? base.slice(0, -1) : base
}

async function fetchPrevious(
  path: string,
  signature: string | null,
): Promise<{ rows: unknown[]; truncated: boolean }> {
  const url = stackBaseUrl() + path
  const res = await fetch(url, {
    method: "POST",
    headers: signature !== null ? { "webhook-signature": signature } : {},
  })
  if (!res.ok) {
    throw new Error(`Could not read the rows this write affects (${res.status})`)
  }
  const body = (await res.json()) as { rows?: unknown[]; truncated?: boolean }
  return { rows: body.rows ?? [], truncated: body.truncated === true }
}

function json(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  })
}
