/**
 * Write a schema containing every declarable field kind.
 *
 * Generated rather than committed, so it cannot drift from {@link KIND_SPECS}: adding a kind there
 * puts it in the schema on the next run, and a kind that stops being declarable fails the build at
 * the `Record<FieldKind, KindSpec>` before it reaches here.
 *
 * Written into its own project directory rather than into `tests/integration/schema`, because this
 * pushes a table, drops columns from it and pushes again. Doing that to the shared fixture would
 * make every other suite's database depend on the order this one ran in.
 */
import { mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { testableKinds } from "./kinds.js"

/** Fields that cannot be written as an ordinary optional column on the probe model. */
const SPECIAL = new Set(["serial", "bigSerial", "relation", "image", "file"])

export function schemaSource(): string {
  const kinds = testableKinds()

  const imports = new Set<string>(["Model", "Optional", "UUID", "Public"])
  for (const [, spec] of kinds) for (const i of spec.imports) imports.add(i)

  const ordinary = kinds.filter(([k]) => !SPECIAL.has(k))
  const fields = ordinary.map(([kind, spec]) => `  ${fieldName(kind)}: ${spec.declare}`)

  return `// Generated by tests/integration/conformance/generate-schema.ts. Do not edit.
//
// One model carrying every declarable field kind, so the conformance harness can assert what each
// one does on a real database: the column it creates, the type the AST publishes, the TypeScript it
// generates, a value round trip, that a second push is a no-op, and that it can be dropped again.
import type {
${[...imports].sort().map((i) => `  ${i},`).join("\n")}
} from "@supatype/types"

/** The far side of the relation under test. */
export type probeTarget = Model<{
  id: UUID
  label: Optional<string>
}, {
  access: { read: Public; create: Public; update: Public; delete: Public }
}>

export type probeAll = Model<{
  id: UUID
  /** Source for the slug kind, which needs a column to derive from. */
  probeText: Optional<string>
${fields.join("\n")}
  target: Optional<RelatedTo<probeTarget>>
}, {
  access: { read: Public; create: Public; update: Public; delete: Public }
}>
`
}

/** The column a kind is declared under, kept stable so assertions can find it. */
export function fieldName(kind: string): string {
  return `probe${kind[0]!.toUpperCase()}${kind.slice(1)}`
}

export function writeSchema(projectDir: string): string {
  const dir = join(projectDir, "schema")
  mkdirSync(dir, { recursive: true })
  const path = join(dir, "index.ts")
  writeFileSync(path, schemaSource(), "utf8")
  return path
}

if (process.argv[2]) {
  const written = writeSchema(process.argv[2])
  console.log(`wrote ${written}`)
}
