export interface AstModel {
  name?: string
  tableName?: string
  fields: Record<string, Record<string, unknown>>
  annotations?: {
    db?: { tableName?: string; indexes?: unknown[] }
  }
}

interface AstShape {
  models?: AstModel[]
}

/**
 * Shared with the hooks generator on purpose.
 *
 * A hook's `row` must be the same shape the client sees for that table, and two copies of this logic
 * would drift: the client would gain a column type the hook handler did not, which is the failure
 * mode this codebase has already paid for once.
 */
export function resolveTableName(model: AstModel): string {
  const fromAnnotations = model.annotations?.db?.tableName
  if (typeof fromAnnotations === "string" && fromAnnotations.length > 0) return fromAnnotations
  if (typeof model.tableName === "string" && model.tableName.length > 0) return model.tableName
  if (typeof model.name === "string" && model.name.length > 0) {
    return model.name.replace(/([A-Z])/g, "_$1").replace(/^_/, "").toLowerCase()
  }
  return "unknown"
}

function fieldServerGenerated(meta: Record<string, unknown>): boolean {
  if (meta["serverGenerated"] === true) return true
  const annotations = meta["annotations"]
  if (typeof annotations !== "object" || annotations === null) return false
  const db = (annotations as { db?: { serverGenerated?: unknown } }).db
  return db?.serverGenerated === true
}

export function generateClientAugmentation(ast: unknown): string {
  const parsed = ast as AstShape
  // In the order the schema declares them. The AST preserves that order, and it is the order
  // the author reads their own schema in.
  const models = [...(parsed.models ?? [])].map((model) => ({
    model,
    tableName: resolveTableName(model),
  }))

  const kinds = new Set<string>()
  for (const { model } of models) {
    for (const meta of Object.values(model.fields ?? {})) {
      if (typeof meta["kind"] === "string") kinds.add(meta["kind"])
    }
  }

  const lines: string[] = []
  lines.push("// Generated by supatype CLI, do not edit manually.")
  lines.push("")
  if (kinds.has("richText")) {
    lines.push("import type { SerializedEditorState } from \"@supatype/types/lexical\"")
    lines.push("")
    lines.push("export type RichText = SerializedEditorState")
    lines.push("")
  }
  if (kinds.has("image") || kinds.has("file")) {
    lines.push("export type StorageReference = {")
    lines.push("  bucket: string")
    lines.push("  path: string")
    lines.push("}")
    lines.push("")
  }
  lines.push("declare module \"@supatype/client\" {")
  lines.push("  interface SupatypeModels {")

  for (const { model, tableName } of models) {
    lines.push(`    ${quoteKey(tableName)}: {`)
    lines.push(`      Row: ${indent(generateRowType(model.fields), 6)}`)
    lines.push(`      Insert: ${indent(generateInsertType(model.fields), 6)}`)
    lines.push(`      Update: ${indent(generateUpdateType(model.fields), 6)}`)
    lines.push("    }")
  }

  lines.push("  }")
  lines.push("}")
  lines.push("")
  lines.push("export {}")
  lines.push("")

  return lines.join("\n")
}

/** Place a generated object body inside the block that holds it. */
function indent(source: string, spaces: number): string {
  const pad = " ".repeat(spaces)
  return source
    .split("\n")
    .map((line, i) => (i === 0 ? line : `${pad}${line}`))
    .join("\n")
}

function toSnakeCase(name: string): string {
  return name.replace(/([A-Z])/g, "_$1").replace(/^_/, "").toLowerCase()
}

/**
 * The column a declared field actually occupies, which is not always the name it was declared under.
 *
 * Only `belongsTo` puts a column on this table, and that column is the foreign key: `speaker_id`
 * holding text, not `speaker` holding the target row. This used to group `relation` with the JSONB
 * kinds, so the augmentation described a column that does not exist while the engine described the
 * one that does, and the two generated files disagreed about the same field. `hasMany`, `hasOne` and
 * `manyToMany` keep their key on the other table, so there is nothing here to describe.
 */
function resolveColumn(
  name: string,
  meta: Record<string, unknown>,
): { column: string; ts: string } | null {
  if (meta["kind"] !== "relation") return { column: name, ts: toTsType(meta) }
  if (meta["cardinality"] !== "belongsTo") return null

  const annotations = meta["annotations"]
  const declared =
    typeof annotations === "object" && annotations !== null
      ? (annotations as { db?: { foreignKey?: unknown } }).db?.foreignKey
      : undefined
  const column =
    typeof declared === "string" && declared.length > 0 ? declared : `${toSnakeCase(name)}_id`

  // Nullable unless the relation asked for `NOT NULL`, which is the engine's rule. A fix that made
  // every foreign key non-nullable would be wrong in the other direction just as often.
  return { column, ts: meta["required"] === true ? "string" : "string | null" }
}

/** Declared fields as the columns they become, dropping the ones that are not columns here. */
function columnsOf(
  fields: Record<string, Record<string, unknown>>,
): Array<{ column: string; ts: string; meta: Record<string, unknown> }> {
  return Object.entries(fields)
    .map(([name, meta]) => {
      const resolved = resolveColumn(name, meta)
      return resolved === null ? null : { ...resolved, meta }
    })
    .filter((entry): entry is { column: string; ts: string; meta: Record<string, unknown> } =>
      entry !== null,
    )
}

export function generateRowType(fields: Record<string, Record<string, unknown>>): string {
  const columns = columnsOf(fields)
  if (columns.length === 0) return "Record<string, unknown>"
  const body = columns.map(({ column, ts }) => `  ${quoteKey(column)}: ${ts}`).join("\n")
  return `{\n${body}\n}`
}

/**
 * What a column accepts on the way in, where that is wider than what it returns.
 *
 * A rich text column holds a Lexical document, and the engine emits a trigger that normalises a
 * plain string into one on insert and update. So writing prose is a string and reading it is
 * always a document, and this is the only place the three shapes differ by more than
 * optionality. Flattening them back would either demand hand-built Lexical JSON from every
 * caller, or claim a read might return a string, which after the trigger it cannot.
 */
function widenForWrites(ts: string, meta: Record<string, unknown>): string {
  // Rebuilt rather than edited. The widening has to land on the value the trigger normalises,
  // and for a localized column that is each locale's value, not the map holding them. Splicing
  // ` | string` into the finished string put it outside the locale wrapper, which said a bare
  // string was a valid write to the column; the trigger would then store it as a single document
  // where a locale map belongs, and the Row type says that cannot happen.
  return meta["kind"] === "richText" ? toTsType(meta, true) : ts
}

function insertColumnOptionalOnInsert(meta: Record<string, unknown>): boolean {
  // `slug` has neither a declared default nor a `serverGenerated` flag, but the engine emits
  // a trigger that fills it, which is the same thing from an insert's point of view.
  return (
    meta["default"] !== undefined || fieldServerGenerated(meta) || meta["kind"] === "slug"
  )
}

export function generateInsertType(fields: Record<string, Record<string, unknown>>): string {
  const columns = columnsOf(fields)
  if (columns.length === 0) return "Record<string, unknown>"
  const body = columns
    .map(({ column, ts, meta }) => {
      const required = meta["required"] === true && !insertColumnOptionalOnInsert(meta)
      return `  ${quoteKey(column)}${required ? "" : "?"}: ${widenForWrites(ts, meta)}`
    })
    .join("\n")
  return `{\n${body}\n}`
}

export function generateUpdateType(fields: Record<string, Record<string, unknown>>): string {
  const columns = columnsOf(fields)
  if (columns.length === 0) return "Record<string, unknown>"
  const body = columns
    .map(({ column, ts, meta }) => `  ${quoteKey(column)}?: ${widenForWrites(ts, meta)}`)
    .join("\n")
  return `{\n${body}\n}`
}

function toTsType(meta: Record<string, unknown>, prose = false): string {
  const kind = typeof meta["kind"] === "string" ? meta["kind"] : "json"
  const required = meta["required"] === true
  const base = (() => {
    // A field that knows its own shape says so. Without this, everything stored as JSONB collapses
    // to `Record<string, unknown>` in the generated row, so `Currency` would arrive as an opaque
    // object rather than `{ amount: string; code: "USD" }`, and the schema's precision would be
    // lost exactly where a caller reads it.
    const declared = meta["tsType"]
    if (typeof declared === "string" && declared.length > 0) return declared
    switch (kind) {
      case "uuid":
      case "slug":
      case "text":
      case "email":
      case "url":
      case "date":
      case "timestamp":
      case "datetime":
      case "money":
      // NUMERIC, and the exact value is the point. A `number` here is the same defect as parsing
      // the wire with `JSON.parse`: `12345678901234567890.1234` has no float representation, so a
      // column declared to hold it would arrive rounded and typed as though it had not been.
      // `@supatype/types` already says so: `Decimal<P, S>` carries `string`.
      case "decimal":
      case "xml":
      case "interval":
        return "string"
      case "integer":
      case "smallInt":
      case "serial":
      case "float":
        return "number"
      case "bigSerial":
      case "bigInt":
        return "bigint"
      case "boolean":
        return "boolean"
      case "json":
      case "blocks":
      case "geo":
      case "vector":
      case "relation":
      case "array":
        return "Record<string, unknown>"
      // What `storage.upload()` actually produces, plus the bucket it went to. Emitting
      // `Record<string, unknown>` here is why two example screens cast on the good path. A `url`
      // is deliberately absent: a stored one goes stale and hard-codes the storage host, so it is
      // derived at read time instead.
      case "image":
      case "file":
        return "StorageReference"
      case "richText":
        return "RichText"
      case "enum": {
        const values = Array.isArray(meta["values"]) ? meta["values"] as unknown[] : []
        const quoted = values
          .filter((v): v is string => typeof v === "string")
          .map((v) => JSON.stringify(v))
        return quoted.length > 0 ? quoted.join(" | ") : "string"
      }
      default:
        return "unknown"
    }
  })()
  // A localized column is JSONB holding a locale map, `{"en": ..., "fr": ...}`, not the bare
  // value. `page.title` is exactly this and was typed `string`, so calling a string method on it
  // compiled and then failed against real data.
  // Prose, which a trigger normalises into a document on the way in. Applied to the element,
  // before the locale wrapper goes on, so a localized column reads `{ [locale: string]: RichText
  // | string }` rather than claiming the whole map could be a string.
  const written = prose && meta["kind"] === "richText" ? `${base} | string` : base
  const shaped = meta["localized"] === true ? `{ [locale: string]: ${written} }` : written
  return required ? shaped : `${shaped} | null`
}

function quoteKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key)
}
