export interface AstModel {
  name?: string
  tableName?: string
  fields: Record<string, Record<string, unknown>>
  annotations?: {
    db?: { tableName?: string; indexes?: unknown[] }
  }
}

interface AstShape {
  models?: AstModel[]
}

/**
 * Shared with the hooks generator on purpose.
 *
 * A hook's `row` must be the same shape the client sees for that table, and two copies of this logic
 * would drift: the client would gain a column type the hook handler did not, which is the failure
 * mode this codebase has already paid for once.
 */
export function resolveTableName(model: AstModel): string {
  const fromAnnotations = model.annotations?.db?.tableName
  if (typeof fromAnnotations === "string" && fromAnnotations.length > 0) return fromAnnotations
  if (typeof model.tableName === "string" && model.tableName.length > 0) return model.tableName
  if (typeof model.name === "string" && model.name.length > 0) {
    return model.name.replace(/([A-Z])/g, "_$1").replace(/^_/, "").toLowerCase()
  }
  return "unknown"
}

function fieldServerGenerated(meta: Record<string, unknown>): boolean {
  if (meta["serverGenerated"] === true) return true
  const annotations = meta["annotations"]
  if (typeof annotations !== "object" || annotations === null) return false
  const db = (annotations as { db?: { serverGenerated?: unknown } }).db
  return db?.serverGenerated === true
}

export function generateClientAugmentation(ast: unknown): string {
  const parsed = ast as AstShape
  const models = [...(parsed.models ?? [])]
    .map((model) => ({ model, tableName: resolveTableName(model) }))
    .sort((a, b) => a.tableName.localeCompare(b.tableName))

  const lines: string[] = []
  lines.push("// Generated by supatype CLI, do not edit manually.")
  lines.push("")
  lines.push("declare module \"@supatype/client\" {")
  lines.push("  interface SupatypeModels {")

  for (const { model, tableName } of models) {
    lines.push(`    ${quoteKey(tableName)}: {`)
    lines.push(`      Row: ${generateRowType(model.fields)}`)
    lines.push(`      Insert: ${generateInsertType(model.fields)}`)
    lines.push(`      Update: ${generateUpdateType(model.fields)}`)
    lines.push("    }")
  }

  lines.push("  }")
  lines.push("}")
  lines.push("")
  lines.push("export {}")
  lines.push("")

  return lines.join("\n")
}

export function generateRowType(fields: Record<string, Record<string, unknown>>): string {
  const entries = Object.entries(fields).sort(([a], [b]) => a.localeCompare(b))
  if (entries.length === 0) return "Record<string, unknown>"
  const body = entries
    .map(([name, meta]) => `  ${quoteKey(name)}: ${toTsType(meta)}`)
    .join("\n")
  return `{\n${body}\n}`
}

function insertColumnOptionalOnInsert(meta: Record<string, unknown>): boolean {
  return meta["default"] !== undefined || fieldServerGenerated(meta)
}

export function generateInsertType(fields: Record<string, Record<string, unknown>>): string {
  const entries = Object.entries(fields).sort(([a], [b]) => a.localeCompare(b))
  if (entries.length === 0) return "Record<string, unknown>"
  const body = entries
    .map(([name, meta]) => {
      const required = meta["required"] === true && !insertColumnOptionalOnInsert(meta)
      return `  ${quoteKey(name)}${required ? "" : "?"}: ${toTsType(meta)}`
    })
    .join("\n")
  return `{\n${body}\n}`
}

export function generateUpdateType(fields: Record<string, Record<string, unknown>>): string {
  const entries = Object.entries(fields).sort(([a], [b]) => a.localeCompare(b))
  if (entries.length === 0) return "Record<string, unknown>"
  const body = entries
    .map(([name, meta]) => `  ${quoteKey(name)}?: ${toTsType(meta)}`)
    .join("\n")
  return `{\n${body}\n}`
}

function toTsType(meta: Record<string, unknown>): string {
  const kind = typeof meta["kind"] === "string" ? meta["kind"] : "json"
  const required = meta["required"] === true
  const base = (() => {
    // A field that knows its own shape says so. Without this, everything stored as JSONB collapses
    // to `Record<string, unknown>` in the generated row, so `Currency` would arrive as an opaque
    // object rather than `{ amount: string; code: "USD" }`, and the schema's precision would be
    // lost exactly where a caller reads it.
    const declared = meta["tsType"]
    if (typeof declared === "string" && declared.length > 0) return declared
    switch (kind) {
      case "uuid":
      case "slug":
      case "text":
      case "email":
      case "url":
      case "date":
      case "timestamp":
      case "datetime":
      case "money":
      case "xml":
      case "interval":
        return "string"
      case "integer":
      case "smallInt":
      case "serial":
      case "float":
      case "decimal":
        return "number"
      case "bigSerial":
      case "bigInt":
        return "bigint"
      case "boolean":
        return "boolean"
      case "json":
      case "blocks":
      case "geo":
      case "vector":
      case "relation":
      case "array":
      case "image":
      case "file":
        return "Record<string, unknown>"
      case "richText":
        return "(import(\"@supatype/types/lexical\").SerializedEditorState | string)"
      case "enum": {
        const values = Array.isArray(meta["values"]) ? meta["values"] as unknown[] : []
        const quoted = values
          .filter((v): v is string => typeof v === "string")
          .map((v) => JSON.stringify(v))
        return quoted.length > 0 ? quoted.join(" | ") : "string"
      }
      default:
        return "unknown"
    }
  })()
  return required ? base : `${base} | null`
}

function quoteKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key)
}
