/**
 * The client a project imports, generated into its own source tree.
 *
 * One file, written by `supatype push`, that an app imports once:
 *
 *     import { createClient } from "./supatype/client"
 *
 * It carries three things that used to arrive by three routes, two of which could fail without
 * saying so.
 *
 * The **module augmentation** was a `.d.ts` that TypeScript found only because the project's
 * tsconfig `include` happened to name the generated directory. Thirteen tsconfig files across the
 * examples named it, one project never named it at all, and in that state `AugmentedTables` falls
 * back to `Record<string, TableDef>`: every table name is accepted, every column is `unknown`, and
 * the build passes. Reaching it by import instead means tsconfig cannot lose it.
 *
 * The **field kinds** were read from `field-kinds.json` on disk, falling back to fetching
 * PostgREST's OpenAPI document. That fallback reconstructs the answer from the live database, so it
 * always succeeds, which made a project that had never generated indistinguishable from one that
 * had. Compiling them in removes both the read and the fallback, and makes absence detectable.
 *
 * And **`createClient`** itself, so the one import is the whole setup. A project that has not
 * generated has no file here to import, so the build fails rather than the app running with a
 * client that knows nothing about its schema.
 */
import { generateClientAugmentation } from "./augmentation-generator.js"

/** The kinds whose values no binary float holds, keyed by the schema kind that produces them. */
const EXACT_KIND_BY_FIELD_KIND: Readonly<Record<string, "bigint" | "numeric">> = {
  bigInt: "bigint",
  bigSerial: "bigint",
  decimal: "numeric",
  money: "numeric",
}

const FORMAT_VERSION = 1

type AstShape = {
  models?: Array<{
    name?: string
    annotations?: Record<string, unknown>
    fields?: Record<string, Record<string, unknown>>
  }>
}

/** The full contents of `supatype/client.ts`. */
export function generateProjectClient(ast: unknown): string {
  // Normalised first: `push` should not die on a malformed AST while writing a file, and the
  // augmentation generator indexes `.models` without checking.
  const safe = ast !== null && typeof ast === "object" ? ast : { models: [] }
  const augmentation = generateClientAugmentation(safe)

  return [
    "// Generated by supatype CLI, do not edit manually.",
    "//",
    "// Import the client from here rather than from `@supatype/client`:",
    "//",
    '//     import { createClient } from "./supatype/client"',
    "//",
    "// This file carries your schema's types and the columns that need exact handling, so one",
    "// import is the whole setup. Importing `@supatype/client` directly gets a client that knows",
    "// nothing about this project.",
    "",
    'import { registerFieldKinds } from "@supatype/client"',
    "",
    augmentationBody(augmentation),
    "",
    "// Columns holding values a JSON parser would round: bigInt, decimal and money. Registered at",
    "// import time, so reading one returns what the database holds rather than the nearest double.",
    `registerFieldKinds(${JSON.stringify(fieldKindsDocument(safe), null, 2)})`,
    "",
    'export * from "@supatype/client"',
    "",
  ].join("\n")
}

/**
 * The augmentation, without the pieces that only made sense in a file of its own.
 *
 * Its header said "generated", which this file says once already, and it ended in `export {}` to
 * make itself a module. This file has imports and exports of its own, so it is one regardless.
 */
function augmentationBody(augmentation: string): string {
  return augmentation
    .replace(/^\/\/ Generated by supatype CLI[^\n]*\n+/, "")
    .replace(/\n*export \{\}\s*$/, "")
    .trimEnd()
}

/** The exact-value columns of every table, as the registry expects them. */
function fieldKindsDocument(ast: unknown): { version: number; tables: Record<string, unknown> } {
  const tables: Record<string, Record<string, string>> = {}

  for (const model of readModels(ast)) {
    const exact: Record<string, string> = {}
    for (const [column, meta] of Object.entries(model.fields ?? {})) {
      const kind = typeof meta["kind"] === "string" ? meta["kind"] : ""
      const exactKind = EXACT_KIND_BY_FIELD_KIND[kind]
      if (exactKind !== undefined) exact[column] = exactKind
    }
    if (Object.keys(exact).length > 0) {
      tables[resolveTableName(model)] = exact
    }
  }

  return { version: FORMAT_VERSION, tables }
}

function resolveTableName(model: { name?: string; annotations?: Record<string, unknown> }): string {
  const db = model.annotations?.["db"]
  if (db !== null && typeof db === "object") {
    const named = (db as { tableName?: unknown }).tableName
    if (typeof named === "string" && named !== "") return named
  }
  return model.name ?? ""
}

function readModels(ast: unknown): NonNullable<AstShape["models"]> {
  if (ast === null || typeof ast !== "object") return []
  const models = (ast as AstShape).models
  return Array.isArray(models) ? models : []
}
