/**
 * Keep `functions/_shared/context.ts` current on a project that already exists.
 *
 * The module is generated by `ensureFunctionsDenoTypes`, which `init` and `supatype functions new`
 * call and nothing else did. So it reached new projects and new functions, and never reached a
 * project that already had functions when the two-argument handler contract landed: those keep
 * `(req)` handlers with no `FunctionContext` to import, while the generated file asserts
 * "Regenerated by the CLI. Edits are overwritten."
 *
 * A claim about a file nothing maintains is worse than no claim, because it tells people not to
 * edit it and not to expect it to change.
 *
 * Only when the project has a functions directory: writing `_shared/` into a project that has no
 * functions would create the thing it describes out of nothing.
 */
import { existsSync } from "node:fs"
import { ensureFunctionsDenoTypes } from "./functions-deno-types.js"
import { preferredFunctionsPathFromProject, type SupatypeProjectConfig } from "./project-config.js"

/** Rewrite the context module. True when this project has functions and one was written. */
export function refreshFunctionsContext(cwd: string, config: SupatypeProjectConfig): boolean {
  const functionsDir = preferredFunctionsPathFromProject(config, cwd)
  if (!existsSync(functionsDir)) return false
  return ensureFunctionsDenoTypes(cwd, functionsDir).wroteContextModule
}
