/**
 * Generates a Deno router entrypoint so `deno run` (optionally `deno run --watch` in dev)
 * can serve multiple handlers (same routing contract as `supatype functions serve`).
 */
import {
  basename,
  join,
  relative,
  dirname,
  resolve as pathResolve,
} from "node:path"
import { existsSync, readdirSync, statSync, mkdirSync, writeFileSync } from "node:fs"

export interface DiscoveredFunctionRoute {
  name: string
  entrypoint: string
}

/** Discover *.ts handlers and `{name}/index.ts` dirs; skips `_shared`, dotfiles. */
export function discoverTsFunctionsInDir(functionsDir: string): DiscoveredFunctionRoute[] {
  if (!existsSync(functionsDir)) return []

  const entries = readdirSync(functionsDir)
  const out: DiscoveredFunctionRoute[] = []

  for (const entry of entries) {
    if (entry.startsWith("_") || entry.startsWith(".")) continue

    const fullPath = join(functionsDir, entry)
    const st = statSync(fullPath)

    if (st.isDirectory()) {
      const indexTs = join(fullPath, "index.ts")
      if (existsSync(indexTs)) out.push({ name: entry, entrypoint: indexTs })
    } else if (entry.endsWith(".ts") && !entry.endsWith(".d.ts")) {
      const name = basename(entry, ".ts")
      out.push({ name, entrypoint: fullPath })
    }
  }

  return out.sort((a, b) => a.name.localeCompare(b.name))
}

function importSpecFromRouter(routerFilePath: string, entrypoint: string): string {
  const rel = relative(dirname(routerFilePath), entrypoint).replace(/\\/g, "/")
  if (!rel.startsWith(".")) return `./${rel}`
  return rel
}

/** Router source rooted at routerFilePath (defines import paths). */
export function generateFunctionsRouterSource(
  routerFilePath: string,
  fns: DiscoveredFunctionRoute[],
): string {
  const imports = fns.map(
    (fn, i) =>
      `import handler_${i} from "${importSpecFromRouter(routerFilePath, fn.entrypoint)}"`,
  )
  const routes = fns.map((fn, i) => `  "${fn.name}": handler_${i},`)

  return `// Auto-generated: do not edit (regenerated by supatype dev / functions serve)
import { AsyncLocalStorage } from "node:async_hooks"
${imports.join("\n")}

/**
 * What a function is told about the call it is serving.
 *
 * Passed as the second argument rather than injected into the process environment, so
 * invocations do not have to
 * be serialised to keep one call's configuration out of another's.
 */
interface FunctionContext {
  readonly executionId: string
  readonly functionName: string
  readonly url: string
  readonly anonKey: string
  readonly serviceRoleKey?: string
  readonly dbUrl?: string
  readonly region: string
  readonly env: Readonly<Record<string, string>>
}

const handlers: Record<string, (req: Request, ctx: FunctionContext) => Response | Promise<Response>> = {
${routes.join("\n")}
}

const port = parseInt(Deno.env.get("PORT") ?? "8001", 10)
const functionsDir = Deno.env.get("SUPATYPE_DENO_FUNCTIONS_DIR") ?? ""
const normalizedFunctionsDir = functionsDir.endsWith("/") ? functionsDir.slice(0, -1) : functionsDir
const sharedEnvPath = Deno.env.get("SUPATYPE_SHARED_ENV_FILE")
  ?? (normalizedFunctionsDir ? normalizedFunctionsDir + "/.env.local" : "")

// Nothing per-invocation is written to Deno.env, so invocations run concurrently.
//
// This used to hold a lock across the whole handler because the config was delivered by mutating
// the process environment, which is global: two concurrent calls would read each other's values.
// The lock made the router run one invocation at a time, so a function waiting on a slow API
// blocked every other function locally, and the deployed worker had the same lock, so local
// behaved exactly like production and the serialisation was invisible.
const invocationStore = new AsyncLocalStorage<{ executionId: string; functionName: string }>()

const realConsole = {
  debug: console.debug.bind(console),
  info: console.info.bind(console),
  log: console.log.bind(console),
  warn: console.warn.bind(console),
  error: console.error.bind(console),
}

function projectRef(): string {
  return (Deno.env.get("SUPATYPE_PROJECT_REF") ?? "").trim() || "unknown"
}

function emit(level: string, message: string, extra: Record<string, unknown> = {}): void {
  const current = invocationStore.getStore()
  const line = {
    timestamp: new Date().toISOString(),
    level,
    service: "functions-worker",
    project_ref: projectRef(),
    ...(current ? { request_id: current.executionId, function: current.functionName } : {}),
    message,
    ...extra,
  }
  const write = level === "error" ? realConsole.error : realConsole.log
  write(JSON.stringify(line))
}

function formatArg(value: unknown): string {
  if (typeof value === "string") return value
  if (value instanceof Error) return value.stack ?? value.name + ": " + value.message
  try {
    return JSON.stringify(value) ?? String(value)
  } catch {
    return String(value)
  }
}

// A function's own console output, structured and attributed to the call that wrote it. Captured
// before any handler runs so nothing it logs escapes unlabelled.
for (const [method, level] of [["debug", "debug"], ["info", "info"], ["log", "info"], ["warn", "warn"], ["error", "error"]] as const) {
  console[method] = (...args: unknown[]): void => {
    emit(level, args.map(formatArg).join(" "))
  }
}

async function readEnvFile(path: string): Promise<Record<string, string>> {
  if (!path) return {}
  try {
    const text = await Deno.readTextFile(path)
    const out: Record<string, string> = {}
    for (const raw of text.split("\\n")) {
      const line = raw.trim()
      if (!line || line.startsWith("#")) continue
      const eq = line.indexOf("=")
      if (eq <= 0) continue
      const key = line.slice(0, eq).trim()
      let value = line.slice(eq + 1).trim()
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1)
      }
      out[key] = value
    }
    return out
  } catch {
    return {}
  }
}

async function scopedEnvForFunction(fnName: string): Promise<Record<string, string>> {
  const shared = await readEnvFile(sharedEnvPath)
  if (!normalizedFunctionsDir) return shared
  const fnVars = await readEnvFile(normalizedFunctionsDir + "/.env." + fnName + ".local")
  return { ...shared, ...fnVars }
}

Deno.serve({
  port,
  onListen: ({ hostname, port: bound }) => {
    emit("info", "functions router listening on http://" + hostname + ":" + bound)
  },
}, async (req: Request): Promise<Response> => {
  const url = new URL(req.url)
  const pathParts = url.pathname
    .replace(/^\\/functions\\/v1\\/?/, "")
    .split("/")
    .filter(Boolean)
  const fnName = pathParts[0] ?? ""

  if (!fnName || !handlers[fnName]) {
    return new Response(JSON.stringify({
      error: "not_found",
      message: fnName ? 'Function "' + fnName + '" not found' : "No function specified",
      available: Object.keys(handlers),
    }), { status: 404, headers: { "Content-Type": "application/json" } })
  }

  const anonKey = Deno.env.get("SUPATYPE_ANON_KEY") ?? ""
  const serviceRoleKey = Deno.env.get("SUPATYPE_SERVICE_ROLE_KEY")
  const dbUrl = Deno.env.get("SUPATYPE_DB_URL") ?? Deno.env.get("DATABASE_URL")
  const context: FunctionContext = {
    executionId: crypto.randomUUID(),
    functionName: fnName,
    url: Deno.env.get("SUPATYPE_URL") ?? "",
    anonKey,
    ...(serviceRoleKey ? { serviceRoleKey } : {}),
    ...(dbUrl ? { dbUrl } : {}),
    region: Deno.env.get("SUPATYPE_REGION") ?? "local",
    env: await scopedEnvForFunction(fnName),
  }

  const start = performance.now()

  try {
    const response = await invocationStore.run(
      { executionId: context.executionId, functionName: fnName },
      async () => handlers[fnName]!(req, context),
    )
    emit("info", req.method + " /functions/v1/" + fnName + " -> " + response.status, {
      status: response.status,
      duration_ms: Number((performance.now() - start).toFixed(1)),
    })
    return response
  } catch (err) {
    emit("error", err instanceof Error ? err.message : "Unknown error", {
      status: 500,
      duration_ms: Number((performance.now() - start).toFixed(1)),
    })
    return new Response(JSON.stringify({
      error: "function_error",
      message: err instanceof Error ? err.message : "Unknown error",
    }), { status: 500, headers: { "Content-Type": "application/json" } })
  }
})
`
}

/**
 * Writes `.supatype/functions-router.ts` under project cwd. Returns absolute path or null if no handlers.
 * Pass `routes` when callers already scanned the dir to avoid duplicate I/O.
 */
export function writeDevFunctionsRouter(
  cwd: string,
  functionsDir: string,
  routes?: DiscoveredFunctionRoute[],
): string | null {
  const fns = routes ?? discoverTsFunctionsInDir(functionsDir)
  if (fns.length === 0) return null

  const supatypeDir = pathResolve(cwd, ".supatype")
  mkdirSync(supatypeDir, { recursive: true })
  const routerPath = join(supatypeDir, "functions-router.ts")
  const src = generateFunctionsRouterSource(routerPath, fns)
  writeFileSync(routerPath, src, "utf8")
  return routerPath
}
