/**
 * Generates a Deno router entrypoint so `deno run` can serve multiple handlers
 * (same routing contract as `supatype functions serve`).
 */
import {
  basename,
  join,
  relative,
  dirname,
  resolve as pathResolve,
} from "node:path"
import { existsSync, readdirSync, statSync, mkdirSync, writeFileSync } from "node:fs"

export interface DiscoveredFunctionRoute {
  name: string
  entrypoint: string
}

/** Discover *.ts handlers and `{name}/index.ts` dirs; skips `_shared`, dotfiles. */
export function discoverTsFunctionsInDir(functionsDir: string): DiscoveredFunctionRoute[] {
  if (!existsSync(functionsDir)) return []

  const entries = readdirSync(functionsDir)
  const out: DiscoveredFunctionRoute[] = []

  for (const entry of entries) {
    if (entry.startsWith("_") || entry.startsWith(".")) continue

    const fullPath = join(functionsDir, entry)
    const st = statSync(fullPath)

    if (st.isDirectory()) {
      const indexTs = join(fullPath, "index.ts")
      if (existsSync(indexTs)) out.push({ name: entry, entrypoint: indexTs })
    } else if (entry.endsWith(".ts") && !entry.endsWith(".d.ts")) {
      const name = basename(entry, ".ts")
      out.push({ name, entrypoint: fullPath })
    }
  }

  return out.sort((a, b) => a.name.localeCompare(b.name))
}

function importSpecFromRouter(routerFilePath: string, entrypoint: string): string {
  const rel = relative(dirname(routerFilePath), entrypoint).replace(/\\/g, "/")
  if (!rel.startsWith(".")) return `./${rel}`
  return rel
}

/** Router source rooted at routerFilePath (defines import paths). */
export function generateFunctionsRouterSource(
  routerFilePath: string,
  fns: DiscoveredFunctionRoute[],
): string {
  const imports = fns.map(
    (fn, i) =>
      `import handler_${i} from "${importSpecFromRouter(routerFilePath, fn.entrypoint)}"`,
  )
  const routes = fns.map((fn, i) => `  "${fn.name}": handler_${i},`)

  return `// Auto-generated — do not edit (regenerated by supatype dev / functions serve)
${imports.join("\n")}

const handlers: Record<string, (req: Request) => Response | Promise<Response>> = {
${routes.join("\n")}
}

const port = parseInt(Deno.env.get("PORT") ?? "8001", 10)
const functionsDir = Deno.env.get("SUPATYPE_DENO_FUNCTIONS_DIR") ?? ""
const normalizedFunctionsDir = functionsDir.endsWith("/") ? functionsDir.slice(0, -1) : functionsDir
const sharedEnvPath = Deno.env.get("SUPATYPE_SHARED_ENV_FILE")
  ?? (normalizedFunctionsDir ? normalizedFunctionsDir + "/.env.local" : "")

let envLock: Promise<void> = Promise.resolve()

async function withEnvLock<T>(run: () => Promise<T>): Promise<T> {
  const prev = envLock
  let release: () => void = () => {}
  envLock = new Promise<void>(resolve => { release = resolve })
  await prev
  try {
    return await run()
  } finally {
    release()
  }
}

async function readEnvFile(path: string): Promise<Record<string, string>> {
  if (!path) return {}
  try {
    const text = await Deno.readTextFile(path)
    const out: Record<string, string> = {}
    for (const line of text.split("\\n")) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith("#")) continue
      const eq = trimmed.indexOf("=")
      if (eq <= 0) continue
      out[trimmed.slice(0, eq)] = trimmed.slice(eq + 1)
    }
    return out
  } catch {
    return {}
  }
}

async function scopedEnvForFunction(fnName: string): Promise<Record<string, string>> {
  const shared = await readEnvFile(sharedEnvPath)
  if (!normalizedFunctionsDir) return shared
  const fnPath = normalizedFunctionsDir + "/.env." + fnName + ".local"
  const fnVars = await readEnvFile(fnPath)
  return { ...shared, ...fnVars }
}

async function runWithScopedEnv<T>(fnName: string, run: () => Promise<T>): Promise<T> {
  return withEnvLock(async () => {
    const scoped = await scopedEnvForFunction(fnName)
    const prev = new Map<string, string | undefined>()
    for (const [k, v] of Object.entries(scoped)) {
      prev.set(k, Deno.env.get(k))
      Deno.env.set(k, v)
    }
    try {
      return await run()
    } finally {
      for (const k of Object.keys(scoped)) {
        const old = prev.get(k)
        if (old === undefined) Deno.env.delete(k)
        else Deno.env.set(k, old)
      }
    }
  })
}

Deno.serve({ port }, async (req: Request): Promise<Response> => {
  const url = new URL(req.url)
  const pathParts = url.pathname
    .replace(/^\\/functions\\/v1\\/?/, "")
    .split("/")
    .filter(Boolean)
  const fnName = pathParts[0] ?? ""

  if (!fnName || !handlers[fnName]) {
    return new Response(JSON.stringify({
      error: "not_found",
      message: fnName ? \`Function "\${fnName}" not found\` : "No function specified",
      available: Object.keys(handlers),
    }), { status: 404, headers: { "Content-Type": "application/json" } })
  }

  try {
    const start = performance.now()
    const response = await runWithScopedEnv(fnName, async () => {
      const prev = new Map<string, string | undefined>()
      const setScoped = (key: string, value: string | undefined) => {
        if (value === undefined || value.length === 0) return
        prev.set(key, Deno.env.get(key))
        Deno.env.set(key, value)
      }

      // Supatype runtime defaults available to every invocation.
      const supatypeUrl = Deno.env.get("SUPATYPE_URL")
      const supatypeAnon = Deno.env.get("SUPATYPE_ANON_KEY")
      const supatypeServiceRole = Deno.env.get("SUPATYPE_SERVICE_ROLE_KEY")
      const supatypeDbUrl = Deno.env.get("SUPATYPE_DB_URL") ?? Deno.env.get("DATABASE_URL")
      const supatypeJwks = Deno.env.get("SUPATYPE_JWKS")

      setScoped("SUPATYPE_URL", supatypeUrl)
      setScoped("SUPATYPE_ANON_KEY", supatypeAnon)
      setScoped("SUPATYPE_SERVICE_ROLE_KEY", supatypeServiceRole)
      setScoped("SUPATYPE_DB_URL", supatypeDbUrl)
      setScoped("SUPATYPE_JWKS", supatypeJwks)
      if (!Deno.env.get("SUPATYPE_PUBLISHABLE_KEYS") && supatypeAnon) {
        setScoped("SUPATYPE_PUBLISHABLE_KEYS", JSON.stringify({ anon: supatypeAnon }))
      }
      if (!Deno.env.get("SUPATYPE_SECRET_KEYS") && supatypeServiceRole) {
        setScoped("SUPATYPE_SECRET_KEYS", JSON.stringify({ service_role: supatypeServiceRole }))
      }

      setScoped("SUPATYPE_REGION", Deno.env.get("SUPATYPE_REGION") ?? "local")
      setScoped("SUPATYPE_EXECUTION_ID", crypto.randomUUID())
      setScoped("DENO_DEPLOYMENT_ID", Deno.env.get("DENO_DEPLOYMENT_ID") ?? "local-dev")

      try {
        return await handlers[fnName]!(req)
      } finally {
        for (const [key, old] of prev.entries()) {
          if (old === undefined) Deno.env.delete(key)
          else Deno.env.set(key, old)
        }
      }
    })
    const duration = (performance.now() - start).toFixed(1)
    console.log(\`\${req.method} /functions/v1/\${fnName} → \${response.status} (\${duration}ms)\`)
    return response
  } catch (err) {
    console.error(\`Error in function "\${fnName}":\`, err)
    return new Response(JSON.stringify({
      error: "function_error",
      message: err instanceof Error ? err.message : "Unknown error",
    }), { status: 500, headers: { "Content-Type": "application/json" } })
  }
})
`
}

/**
 * Writes `.supatype/functions-router.ts` under project cwd. Returns absolute path or null if no handlers.
 * Pass `routes` when callers already scanned the dir to avoid duplicate I/O.
 */
export function writeDevFunctionsRouter(
  cwd: string,
  functionsDir: string,
  routes?: DiscoveredFunctionRoute[],
): string | null {
  const fns = routes ?? discoverTsFunctionsInDir(functionsDir)
  if (fns.length === 0) return null

  const supatypeDir = pathResolve(cwd, ".supatype")
  mkdirSync(supatypeDir, { recursive: true })
  const routerPath = join(supatypeDir, "functions-router.ts")
  const src = generateFunctionsRouterSource(routerPath, fns)
  writeFileSync(routerPath, src, "utf8")
  return routerPath
}
