import { createHash } from "node:crypto"

/** PgBouncer md5 auth: "md5" + md5(password + username) — same as supatype-cloud / self-host. */
export function pgbouncerMd5Hash(password: string, username: string): string {
  return "md5" + createHash("md5").update(password + username).digest("hex")
}

/** Two roles used by local compose: superuser pools (GoTrue, engine) and PostgREST. */
export function pgbouncerUserlistContent(pgPassword: string): string {
  return `# PgBouncer md5 userlist — matches supatype-cloud transaction pool (auth_type = md5).
# Regenerated by supatype dev --local / init from POSTGRES_PASSWORD.
"supatype_admin" "${pgbouncerMd5Hash(pgPassword, "supatype_admin")}"
"authenticator" "${pgbouncerMd5Hash(pgPassword, "authenticator")}"
`
}
