import { existsSync, mkdirSync, writeFileSync } from "node:fs"
import { dirname, join, relative, resolve } from "node:path"
import { spawnSync } from "node:child_process"
import type { SupatypeProjectConfig } from "./project-config.js"
import { buildKongDeclarative } from "./kong-config.js"

export interface SelfHostComposePaths {
  dir: string
  composePath: string
  kongPath: string
  nginxPath: string
}

export function selfHostComposePaths(cwd: string): SelfHostComposePaths {
  const dir = resolve(cwd, ".supatype", "self-host")
  return {
    dir,
    composePath: join(dir, "docker-compose.yml"),
    kongPath: join(dir, "kong.yml"),
    nginxPath: join(dir, "nginx.conf"),
  }
}

export function appUpstreamForCompose(config: SupatypeProjectConfig): string | undefined {
  if (config.app.mode !== "proxy") return undefined
  const upstream = config.app.upstream?.trim()
  return upstream && upstream.length > 0 ? upstream : undefined
}

export function staticDirForCompose(config: SupatypeProjectConfig): string | undefined {
  if (config.app.mode !== "static") return undefined
  const dir = config.app.static_dir?.trim()
  return dir && dir.length > 0 ? dir : "./public"
}

export function renderSelfHostCompose(config: SupatypeProjectConfig, cwd: string = process.cwd()): string {
  const staticDir = staticDirForCompose(config)
  const staticMountPath = staticDir
    ? staticVolumePathFromProject(cwd, staticDir)
    : undefined
  const staticService = staticDir
    ? `
  static-app:
    image: nginx:alpine
    volumes:
      - ${staticMountPath}:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "8080"
`
    : ""
  const kongDependsOnStatic = staticDir ? "\n      - static-app" : ""

  return `# Generated by supatype self-host compose
services:
  db:
    image: \${SUPATYPE_POSTGRES_IMAGE:-supatype/postgres:17-latest}
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-supatype_admin}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: \${POSTGRES_DB:-supatype}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-supatype_admin}"]
      interval: 5s
      timeout: 5s
      retries: 20

  server:
    image: \${SUPATYPE_SERVER_IMAGE:-\${SUPATYPE_AUTH_IMAGE:-supatype/auth:v1.0.0}}
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: \${API_EXTERNAL_URL:-http://localhost:18473}
      GOTRUE_API_EXTERNAL_URL: \${API_EXTERNAL_URL:-http://localhost:18473}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: "postgres://\${POSTGRES_USER:-supatype_admin}:\${POSTGRES_PASSWORD:-postgres}@db:5432/\${POSTGRES_DB:-supatype}?search_path=auth"
      GOTRUE_SITE_URL: \${SITE_URL:-http://localhost:3000}
      GOTRUE_JWT_SECRET: \${JWT_SECRET:-super-secret-jwt-token-change-in-production}
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_MAILER_AUTOCONFIRM: \${GOTRUE_MAILER_AUTOCONFIRM:-true}
      GOTRUE_DISABLE_SIGNUP: \${DISABLE_SIGNUP:-false}
    ports:
      - "9999:9999"
    depends_on:
      db:
        condition: service_healthy

  postgrest:
    image: postgrest/postgrest:v12.2.8
    environment:
      PGRST_DB_URI: postgresql://\${POSTGRES_USER:-supatype_admin}:\${POSTGRES_PASSWORD:-postgres}@db:5432/\${POSTGRES_DB:-supatype}
      PGRST_DB_SCHEMA: "public, supatype"
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: \${JWT_SECRET:-super-secret-jwt-token-change-in-production}
      PGRST_DB_EXTRA_SEARCH_PATH: public,extensions
      PGRST_DB_POOL: 3
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  storage:
    image: \${SUPATYPE_STORAGE_IMAGE:-supatype/storage:latest}
    environment:
      PORT: 5000
      DATABASE_URL: "postgresql://\${POSTGRES_USER:-supatype_admin}:\${POSTGRES_PASSWORD:-postgres}@db:5432/\${POSTGRES_DB:-supatype}"
      JWT_SECRET: \${JWT_SECRET:-super-secret-jwt-token-change-in-production}
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY: supatype
      S3_SECRET_KEY: supatype-secret
      S3_FORCE_PATH_STYLE: "true"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  realtime:
    image: \${SUPATYPE_REALTIME_IMAGE:-supatype/realtime:latest}
    environment:
      PORT: 4000
      DATABASE_URL: "postgresql://\${POSTGRES_USER:-supatype_admin}:\${POSTGRES_PASSWORD:-postgres}@db:5432/\${POSTGRES_DB:-supatype}"
      JWT_SECRET: \${JWT_SECRET:-super-secret-jwt-token-change-in-production}
      REPLICATION_MODE: RLS
      REPLICATION_POLL_INTERVAL: 100
      SECURE_CHANNELS: "true"
      SLOT_NAME: realtime_slot
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: supatype
      MINIO_ROOT_PASSWORD: supatype-secret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  studio:
    image: \${SUPATYPE_STUDIO_IMAGE:-supatype/studio:latest}
    ports:
      - "3002:3002"

  engine:
    image: \${SUPATYPE_SCHEMA_ENGINE_IMAGE:-supatype/schema-engine:v0.1.0-alpha.3}
    environment:
      ENGINE_PORT: "7500"
      RUST_LOG: info
      DATABASE_URL: postgresql://\${POSTGRES_USER:-supatype_admin}:\${POSTGRES_PASSWORD:-postgres}@db:5432/\${POSTGRES_DB:-supatype}
    ports:
      - "7500:7500"
    depends_on:
      db:
        condition: service_healthy

  kong:
    image: kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    volumes:
      - ./kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "18473:8000"
    depends_on:
      - postgrest
      - server
      - storage
      - realtime
      - studio${kongDependsOnStatic}
${staticService}
volumes:
  db-data:
  minio-data:
`
}

export function writeSelfHostCompose(cwd: string, config: SupatypeProjectConfig): SelfHostComposePaths {
  const paths = selfHostComposePaths(cwd)
  mkdirSync(paths.dir, { recursive: true })
  const staticDir = staticDirForCompose(config)
  const staticAppServiceUrl = staticDir ? "http://static-app:8080" : undefined
  writeFileSync(paths.composePath, renderSelfHostCompose(config, cwd), "utf8")
  writeFileSync(
    paths.kongPath,
    buildKongDeclarative({
      appUpstream: appUpstreamForCompose(config),
      ...(staticAppServiceUrl !== undefined && { staticAppServiceUrl }),
    }),
    "utf8",
  )
  if (staticDir) {
    writeFileSync(paths.nginxPath, renderStaticNginxConf(), "utf8")
  }
  return paths
}

export function runDockerCompose(composePath: string, args: string[], projectRoot: string = process.cwd()): number {
  const envFile = resolve(projectRoot, ".env")
  const composeArgs = ["compose", "-f", composePath]
  if (existsSync(envFile)) {
    composeArgs.push("--env-file", envFile)
  }
  composeArgs.push(...args)
  const result = spawnSync(
    "docker",
    composeArgs,
    { stdio: "inherit", cwd: dirname(composePath) },
  )
  return result.status ?? 1
}

function staticVolumePathFromProject(cwd: string, staticDir: string): string {
  const composeDir = resolve(cwd, ".supatype", "self-host")
  const absStaticDir = resolve(cwd, staticDir)
  let relStaticDir = relative(composeDir, absStaticDir).replace(/\\/g, "/")
  if (!relStaticDir.startsWith(".") && !relStaticDir.startsWith("/")) {
    relStaticDir = `./${relStaticDir}`
  }
  return relStaticDir
}

function renderStaticNginxConf(): string {
  return `server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
`
}
