import { existsSync, mkdirSync, writeFileSync } from "node:fs"
import { dirname, join, relative, resolve } from "node:path"
import { spawnSync } from "node:child_process"
import type { SupatypeProjectConfig } from "./project-config.js"
import { buildKongDeclarative } from "./kong-config.js"

export interface SelfHostComposePaths {
  dir: string
  composePath: string
  kongPath: string
  nginxPath: string
}

export function selfHostComposePaths(cwd: string): SelfHostComposePaths {
  const dir = resolve(cwd, ".supatype", "self-host")
  return {
    dir,
    composePath: join(dir, "docker-compose.yml"),
    kongPath: join(dir, "kong.yml"),
    nginxPath: join(dir, "nginx.conf"),
  }
}

export function appUpstreamForCompose(config: SupatypeProjectConfig): string | undefined {
  if (config.app.mode !== "proxy") return undefined
  const upstream = config.app.upstream?.trim()
  return upstream && upstream.length > 0 ? upstream : undefined
}

export function staticDirForCompose(config: SupatypeProjectConfig): string | undefined {
  if (config.app.mode !== "static") return undefined
  const dir = config.app.static_dir?.trim()
  return dir && dir.length > 0 ? dir : "./public"
}

function projectMountPath(cwd: string): string {
  const composeDir = resolve(cwd, ".supatype", "self-host")
  let rel = relative(composeDir, resolve(cwd)).replace(/\\/g, "/")
  if (!rel.startsWith(".") && !rel.startsWith("/")) {
    rel = `./${rel}`
  }
  return rel || "../.."
}

function serverAppEnvForCompose(config: SupatypeProjectConfig): string {
  const mode = config.app.mode ?? "none"
  const lines = [`      SUPATYPE_APP_MODE: ${mode}`]
  if (mode === "static") {
    const dir = staticDirForCompose(config) ?? "./public"
    lines.push(`      SUPATYPE_APP_STATIC_DIR: /project/${dir.replace(/^\.\//, "")}`)
  } else if (mode === "proxy" && config.app.upstream?.trim()) {
    lines.push(`      SUPATYPE_APP_UPSTREAM: ${config.app.upstream.trim()}`)
  }
  return lines.join("\n")
}

export function renderSelfHostCompose(config: SupatypeProjectConfig, cwd: string = process.cwd()): string {
  const projectMount = projectMountPath(cwd)
  const appEnv = serverAppEnvForCompose(config)

  return `# Generated by supatype self-host compose
# Kong → supatype-server (unified gateway) → internal PostgREST / storage / etc.
services:
  db:
    image: \${SUPATYPE_POSTGRES_IMAGE:-supatype/postgres:17-latest}
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-supatype_admin}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: \${POSTGRES_DB:-supatype}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-supatype_admin}"]
      interval: 5s
      timeout: 5s
      retries: 20

  postgrest:
    image: postgrest/postgrest:v12.2.8
    expose:
      - "3000"
    environment:
      PGRST_DB_URI: postgresql://\${POSTGRES_USER:-supatype_admin}:\${POSTGRES_PASSWORD:-postgres}@db:5432/\${POSTGRES_DB:-supatype}
      PGRST_DB_SCHEMA: "public, supatype"
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: \${JWT_SECRET:-super-secret-jwt-token-change-in-production}
      PGRST_DB_EXTRA_SEARCH_PATH: public,extensions
      PGRST_DB_POOL: 3
    depends_on:
      db:
        condition: service_healthy

  storage:
    image: \${SUPATYPE_STORAGE_IMAGE:-supatype/storage:latest}
    expose:
      - "5000"
    environment:
      PORT: 5000
      DATABASE_URL: "postgresql://\${POSTGRES_USER:-supatype_admin}:\${POSTGRES_PASSWORD:-postgres}@db:5432/\${POSTGRES_DB:-supatype}"
      JWT_SECRET: \${JWT_SECRET:-super-secret-jwt-token-change-in-production}
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY: supatype
      S3_SECRET_KEY: supatype-secret
      S3_FORCE_PATH_STYLE: "true"
    depends_on:
      db:
        condition: service_healthy

  functions-worker:
    image: \${SUPATYPE_FUNCTIONS_WORKER_IMAGE:-supatype/functions-worker:latest}
    expose:
      - "8001"
    volumes:
      - ${projectMount}:/project:ro
    environment:
      SUPATYPE_FUNCTIONS_ROOT: /project/functions
      SUPATYPE_DENO_FUNCTIONS_DIR: /project/functions
      PORT: "8001"
      SUPATYPE_URL: \${API_EXTERNAL_URL:-http://localhost:18473}
      SUPATYPE_ANON_KEY: \${ANON_KEY:-}
      SUPATYPE_SERVICE_ROLE_KEY: \${SERVICE_ROLE_KEY:-}
    depends_on:
      db:
        condition: service_healthy

  server:
    image: \${SUPATYPE_SERVER_IMAGE:-\${SUPATYPE_AUTH_IMAGE:-supatype/server:latest}}
    ports:
      - "9999:9999"
    volumes:
      - ${projectMount}:/project:ro
    working_dir: /project
    environment:
      SUPATYPE_MODE: standalone
      SUPATYPE_MANIFEST_PATH: /project/.supatype/manifest.json
      SUPATYPE_ADMIN_CONFIG_PATH: /project/.supatype/admin-config.json
      SUPATYPE_API_CONFIG_PATH: /project/.supatype/api-config.json
      SUPATYPE_POSTGREST_URL: http://postgrest:3000
      SUPATYPE_GRAPHQL_URL: http://postgrest:3000
      SUPATYPE_STORAGE_URL: http://storage:5000
      SUPATYPE_URL: \${API_EXTERNAL_URL:-http://localhost:18473}
      SUPATYPE_ANON_KEY: \${ANON_KEY:-}
      SUPATYPE_SERVICE_ROLE_KEY: \${SERVICE_ROLE_KEY:-}
      SUPATYPE_SQL_DATABASE_URL: "postgresql://\${POSTGRES_USER:-supatype_admin}:\${POSTGRES_PASSWORD:-postgres}@db:5432/\${POSTGRES_DB:-supatype}"
      SUPATYPE_DENO_FUNCTIONS_DIR: /project/functions
      SUPATYPE_FUNCTIONS_WORKER_URL: http://functions-worker:8001
${appEnv}
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: \${API_EXTERNAL_URL:-http://localhost:18473}
      GOTRUE_API_EXTERNAL_URL: \${API_EXTERNAL_URL:-http://localhost:18473}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: "postgres://\${POSTGRES_USER:-supatype_admin}:\${POSTGRES_PASSWORD:-postgres}@db:5432/\${POSTGRES_DB:-supatype}?search_path=auth"
      GOTRUE_SITE_URL: \${SITE_URL:-http://localhost:3000}
      GOTRUE_JWT_SECRET: \${JWT_SECRET:-super-secret-jwt-token-change-in-production}
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_ADMIN_ROLES: service_role,supatype_admin
      GOTRUE_MAILER_AUTOCONFIRM: \${GOTRUE_MAILER_AUTOCONFIRM:-true}
      GOTRUE_DISABLE_SIGNUP: \${DISABLE_SIGNUP:-false}
    depends_on:
      db:
        condition: service_healthy
      postgrest:
        condition: service_started
      storage:
        condition: service_started
      functions-worker:
        condition: service_started

  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: supatype
      MINIO_ROOT_PASSWORD: supatype-secret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  studio:
    image: \${SUPATYPE_STUDIO_IMAGE:-supatype/studio:latest}
    expose:
      - "3002"

  kong:
    image: kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    volumes:
      - ./kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "18473:8000"
    depends_on:
      - server
      - studio

volumes:
  db-data:
  minio-data:
`
}

function ensureComposeManifest(cwd: string): void {
  const manifestPath = join(cwd, ".supatype", "manifest.json")
  if (existsSync(manifestPath)) return
  mkdirSync(dirname(manifestPath), { recursive: true })
  const manifest = {
    schema: "public",
    postgrest_url: "http://postgrest:3000",
    storage_url: "http://storage:5000",
    realtime_enabled: true,
    functions_enabled: false,
  }
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8")
}

export function writeSelfHostCompose(cwd: string, config: SupatypeProjectConfig): SelfHostComposePaths {
  const paths = selfHostComposePaths(cwd)
  mkdirSync(paths.dir, { recursive: true })
  ensureComposeManifest(cwd)
  writeFileSync(paths.composePath, renderSelfHostCompose(config, cwd), "utf8")
  writeFileSync(
    paths.kongPath,
    buildKongDeclarative({
      unifiedGateway: true,
    }),
    "utf8",
  )
  return paths
}

export function runDockerCompose(composePath: string, args: string[], projectRoot: string = process.cwd()): number {
  const envFile = resolve(projectRoot, ".env")
  const composeArgs = ["compose", "-f", composePath]
  if (existsSync(envFile)) {
    composeArgs.push("--env-file", envFile)
  }
  composeArgs.push(...args)
  const result = spawnSync(
    "docker",
    composeArgs,
    { stdio: "inherit", cwd: dirname(composePath) },
  )
  return result.status ?? 1
}
