/**
 * What a deployment looks like the moment before it has been fully upgraded.
 *
 * The access rules a bucket declares are enforced by asking Postgres, which means the caller's
 * role needs SELECT on `storage.objects`. That grant is generated by the engine and applied by
 * `supatype push`, not carried inside the storage image. So an operator who pulls new images and
 * restarts, and stops there, has a service that asks a question the database refuses to answer.
 *
 * Measured against a live stack with the grant revoked: every private bucket read came back 500,
 * with `permission denied for table objects` in the log and nothing saying what to do about it.
 * A 500 is the wrong answer twice over. It reads as a broken service rather than an unfinished
 * upgrade, and an error on the deny path is the shape of thing that later gets "fixed" by
 * treating the failure as success.
 *
 * So the refusal is deliberate and the SQLSTATE is pinned here, because it is the one detail that
 * decides whether this path fails closed with an explanation or crashes.
 */
import { describe, expect, it } from "vitest"
import { isMissingGrant } from "../src/pg-errors.js"

/** What `pg` throws: an Error carrying the SQLSTATE on `code`. */
function pgError(code: string, message = "permission denied for table objects"): Error {
  return Object.assign(new Error(message), { code })
}

describe("isMissingGrant", () => {
  it("recognises insufficient_privilege, which is what a missing grant raises", () => {
    expect(isMissingGrant(pgError("42501"))).toBe(true)
  })

  it("does not claim any other database error", () => {
    // Each of these is a real fault that must keep propagating. Swallowing one would turn a broken
    // deployment into a silent refusal, which is the failure mode this whole check exists to make
    // legible rather than to spread.
    for (const code of ["42P01", "23505", "08006", "57014", "40001"]) {
      expect(isMissingGrant(pgError(code)), `SQLSTATE ${code}`).toBe(false)
    }
  })

  it("does not match on the message, which is not a contract", () => {
    // The wording is Postgres's and varies by locale and version. The SQLSTATE does not.
    expect(isMissingGrant(new Error("permission denied for table objects"))).toBe(false)
  })

  it("survives the things that are not errors at all", () => {
    for (const value of [null, undefined, "42501", 42501, {}]) {
      expect(isMissingGrant(value)).toBe(false)
    }
  })
})
