/**
 * The client a project imports, generated into its own source tree.
 *
 * An app writes one import and nothing else:
 *
 *     import { createClient } from "./supatype/client"
 *
 * That single file carries three things that previously arrived by three different routes, two of
 * which could silently fail:
 *
 *   the module augmentation  was a `.d.ts` found only through tsconfig `include`, so a stale or
 *                            missing entry left every table name accepted and every column
 *                            `unknown`, with the build passing
 *   the field kinds          were read off disk and, failing that, reconstructed from PostgREST's
 *                            OpenAPI document, which always succeeds and so could never report a
 *                            project that had not generated
 *   `createClient`           came from the package, which knows nothing about the project
 *
 * Arriving by import means the bundler carries them, tsconfig cannot lose them, nothing is
 * fetched, and a project that has not generated has no file to import, so the build fails.
 */
import { describe, expect, it } from "vitest"
import { generateProjectClient } from "../src/client-generator.js"

const ast = {
  models: [
    {
      name: "JobPost",
      annotations: { db: { tableName: "job_post" } },
      fields: {
        id: { kind: "uuid", required: true },
        title: { kind: "text", required: true },
        views: { kind: "bigInt", required: true },
        equityPct: { kind: "decimal", required: false },
      },
    },
  ],
}

const plainAst = {
  models: [
    {
      name: "LandingPage",
      annotations: { db: { tableName: "landing_page" } },
      fields: { id: { kind: "uuid", required: true } },
    },
  ],
}

describe("generateProjectClient", () => {
  it("re-exports the client package, so one import is enough", () => {
    expect(generateProjectClient(ast)).toContain('export * from "@supatype/client"')
  })

  it("carries the module augmentation, rather than relying on tsconfig to find it", () => {
    const out = generateProjectClient(ast)
    expect(out).toContain('declare module "@supatype/client"')
    expect(out).toContain("interface SupatypeModels")
    expect(out).toContain("job_post")
  })

  it("registers the columns a JSON parser would destroy", () => {
    const out = generateProjectClient(ast)
    expect(out).toContain("registerFieldKinds(")
    expect(out).toContain('"views": "bigint"')
    expect(out).toContain('"equityPct": "numeric"')
  })

  it("leaves ordinary columns out of the registration", () => {
    // Listing a column that survives a parse would invite the client to convert one that was
    // already correct.
    const out = generateProjectClient(ast)
    expect(out).not.toContain('"title"')
    expect(out).not.toContain('"id": "')
  })

  it("still registers for a schema with nothing exact", () => {
    // Registered-and-empty is how the client tells "this project generated and has no exact
    // columns" from "this project never generated". Both must not look the same.
    const out = generateProjectClient(plainAst)
    expect(out).toContain("registerFieldKinds(")
    expect(out).toContain('"tables": {}')
  })

  it("imports the registration function from the package", () => {
    expect(generateProjectClient(ast)).toContain(
      'import { registerFieldKinds } from "@supatype/client"',
    )
  })

  it("says it is generated, on the first line", () => {
    expect(generateProjectClient(ast).split("\n")[0]).toContain("Generated by supatype")
  })

  it("is stable across runs, so it does not churn the diff", () => {
    expect(generateProjectClient(ast)).toBe(generateProjectClient(ast))
  })

  it("survives an ast it does not recognise", () => {
    expect(() => generateProjectClient({})).not.toThrow()
    expect(() => generateProjectClient(null)).not.toThrow()
  })
})
