/**
 * `functions/_shared/context.ts` reaches a project that already exists.
 *
 * The module was written by `init` and `supatype functions new`, and by nothing else. So it arrived
 * with new projects and new functions, and never arrived at a project that already had functions
 * when the two-argument handler contract landed: those keep `(req)` handlers with no
 * `FunctionContext` to import, while the generated file itself asserts
 *
 *   Regenerated by the CLI. Edits are overwritten.
 *
 * which was true only if you scaffolded again. `tests/integration` in this repo had four functions
 * and no context module at all, which is how it was found.
 */
import { describe, expect, it, beforeEach, afterEach } from "vitest"
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { refreshFunctionsContext } from "../src/functions-context-refresh.js"
import type { SupatypeProjectConfig } from "../src/project-config.js"

const config: SupatypeProjectConfig = {
  project: { name: "ctx" },
  database: { provider: "docker" },
} as SupatypeProjectConfig

let dir: string

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "supatype-ctx-"))
})

afterEach(() => {
  rmSync(dir, { recursive: true, force: true })
})

/** A project with functions but no `_shared`, which is what a pre-migration project looks like. */
function projectWithFunctions(): string {
  const functions = join(dir, "functions")
  mkdirSync(functions, { recursive: true })
  writeFileSync(
    join(functions, "ping.ts"),
    "export default function ping(_req: Request) { return new Response('ok') }\n",
    "utf8",
  )
  return functions
}

describe("a project that already has functions", () => {
  it("gets the context module written", () => {
    const functions = projectWithFunctions()
    expect(existsSync(join(functions, "_shared", "context.ts"))).toBe(false)

    expect(refreshFunctionsContext(dir, config)).toBe(true)
    expect(existsSync(join(functions, "_shared", "context.ts"))).toBe(true)
  })

  it("writes a module that actually declares the contract", () => {
    // Not merely that a file appeared. The point is the type handlers import.
    projectWithFunctions()
    refreshFunctionsContext(dir, config)
    const source = readFileSync(join(dir, "functions", "_shared", "context.ts"), "utf8")
    expect(source).toContain("FunctionContext")
    expect(source).toContain("executionId")
  })

  it("rewrites a stale copy rather than leaving it", () => {
    // The file says edits are overwritten, so they have to be.
    const functions = projectWithFunctions()
    mkdirSync(join(functions, "_shared"), { recursive: true })
    writeFileSync(join(functions, "_shared", "context.ts"), "// stale\n", "utf8")

    refreshFunctionsContext(dir, config)
    const source = readFileSync(join(functions, "_shared", "context.ts"), "utf8")
    expect(source).not.toBe("// stale\n")
    expect(source).toContain("FunctionContext")
  })
})

describe("a project with no functions", () => {
  it("is left alone", () => {
    // Writing `_shared/` into a project with no functions would create the thing it describes out
    // of nothing, and leave a directory nobody asked for in the diff.
    expect(refreshFunctionsContext(dir, config)).toBe(false)
    expect(existsSync(join(dir, "functions"))).toBe(false)
  })
})
